### ISSUE TITLE
Auto scroll when at end of grid?

### ISSUE THREAD

**Issue by techker** [oleksandrbalan/programguide#2]
is there a way to have autoscroll when at end of page without click?For Tv.

Thx

**Comment by oleksandrbalan** [comment]
I am not sure what do you mean with autoscroll at end of page?

Maybe you are interesting in observing the scroll state?

If so, you could check `state.minaBoxState.translate` property, which holds the observable translation of the program guide. Be aware to wrap it inside `derivedStateOf`, as translation may change frequently when user scrolls in the layout. For example to conditionally show next button when user scrolls near (48dp) the right side of the layout you may use this code:

```kotlin
val buttonVisibilityThreshold = LocalDensity.current.run { 48.dp.toPx() }
val showNext by remember {
    derivedStateOf {
        val translate = state.minaBoxState.translate
        if (translate == null) {
            false
        } else {
            translate.maxX - translate.x < buttonVisibilityThreshold
        }
    }
}
if (showNext) { ... }
```

Check [ProgramGuideStateScreen](https://github.com/oleksandrbalan/programguide/blob/main/demo/src/main/java/eu/wewox/programguide/demo/screens/ProgramGuideStateScreen.kt) where buttons prev / next are shown / hidden according to the scroll state.

https://github.com/oleksandrbalan/programguide/assets/20944869/d9bcf8c6-f457-4b98-90b1-1fedca61c8b1

**Comment by techker** [comment]
good, the issue is i want to mek it like a real eog.no arrows when i get to
the edge if the screen to leap to next rows. instead when you scroll it
moves like if it was endless.

il try out the code to see.Thx!
